//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package xml.xsd;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Tipo di elemento recante informazioni di carattere
 * 				amministrativo. È la parte che più probabilmente
 * 				richiederà aggiustamenti per soddisfare le esigenze di
 * 				vari enti. Molti elementi sono auto-esplicativi.
 * 			
 * 
 * <p>Java class for amministrativaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amministrativaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codice-fiscale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="partita-IVA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="autonoma" type="{}siNoType" minOccurs="0"/>
 *         &lt;element name="ente" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tipologia-amministrativa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="tipologia-funzionale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="stato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="codice-fiscale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="partita-IVA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="funzione-obiettivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="regolamento" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="norma" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="carta-servizi" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="servizio" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="deposito-legale" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="anno-inizio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="strutture" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="scaffalature" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="magazzino" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="pubbliche" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="superficie" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="al-pubblico" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="postazioni" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="lettura" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                             &lt;element name="video" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                             &lt;element name="audio" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                             &lt;element name="internet" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="utenti" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ultimo-anno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="iscritti-prestito" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="minori-quattordici-anni" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="personale" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="temporaneo" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="part-time" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="esterno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bilancio" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="entrate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="uscite" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="personale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="funzionamento" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="automazione" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="patrimonio" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="altre" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amministrativaType", propOrder = {
    "codiceFiscale",
    "partitaIVA",
    "autonoma",
    "ente",
    "regolamento",
    "cartaServizi",
    "depositoLegale",
    "strutture",
    "utenti",
    "personale",
    "bilancio"
})
public class AmministrativaType {

    @XmlElement(name = "codice-fiscale")
    protected String codiceFiscale;
    @XmlElement(name = "partita-IVA")
    protected String partitaIVA;
    protected SiNoType autonoma;
    protected AmministrativaType.Ente ente;
    protected AmministrativaType.Regolamento regolamento;
    @XmlElement(name = "carta-servizi")
    protected AmministrativaType.CartaServizi cartaServizi;
    @XmlElement(name = "deposito-legale")
    protected List<AmministrativaType.DepositoLegale> depositoLegale;
    protected AmministrativaType.Strutture strutture;
    protected AmministrativaType.Utenti utenti;
    protected AmministrativaType.Personale personale;
    protected AmministrativaType.Bilancio bilancio;

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the partitaIVA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitaIVA() {
        return partitaIVA;
    }

    /**
     * Sets the value of the partitaIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitaIVA(String value) {
        this.partitaIVA = value;
    }

    /**
     * Gets the value of the autonoma property.
     * 
     * @return
     *     possible object is
     *     {@link SiNoType }
     *     
     */
    public SiNoType getAutonoma() {
        return autonoma;
    }

    /**
     * Sets the value of the autonoma property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNoType }
     *     
     */
    public void setAutonoma(SiNoType value) {
        this.autonoma = value;
    }

    /**
     * Gets the value of the ente property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.Ente }
     *     
     */
    public AmministrativaType.Ente getEnte() {
        return ente;
    }

    /**
     * Sets the value of the ente property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.Ente }
     *     
     */
    public void setEnte(AmministrativaType.Ente value) {
        this.ente = value;
    }

    /**
     * Gets the value of the regolamento property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.Regolamento }
     *     
     */
    public AmministrativaType.Regolamento getRegolamento() {
        return regolamento;
    }

    /**
     * Sets the value of the regolamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.Regolamento }
     *     
     */
    public void setRegolamento(AmministrativaType.Regolamento value) {
        this.regolamento = value;
    }

    /**
     * Gets the value of the cartaServizi property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.CartaServizi }
     *     
     */
    public AmministrativaType.CartaServizi getCartaServizi() {
        return cartaServizi;
    }

    /**
     * Sets the value of the cartaServizi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.CartaServizi }
     *     
     */
    public void setCartaServizi(AmministrativaType.CartaServizi value) {
        this.cartaServizi = value;
    }

    /**
     * Gets the value of the depositoLegale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the depositoLegale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepositoLegale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmministrativaType.DepositoLegale }
     * 
     * 
     */
    public List<AmministrativaType.DepositoLegale> getDepositoLegale() {
        if (depositoLegale == null) {
            depositoLegale = new ArrayList<AmministrativaType.DepositoLegale>();
        }
        return this.depositoLegale;
    }

    /**
     * Gets the value of the strutture property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.Strutture }
     *     
     */
    public AmministrativaType.Strutture getStrutture() {
        return strutture;
    }

    /**
     * Sets the value of the strutture property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.Strutture }
     *     
     */
    public void setStrutture(AmministrativaType.Strutture value) {
        this.strutture = value;
    }

    /**
     * Gets the value of the utenti property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.Utenti }
     *     
     */
    public AmministrativaType.Utenti getUtenti() {
        return utenti;
    }

    /**
     * Sets the value of the utenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.Utenti }
     *     
     */
    public void setUtenti(AmministrativaType.Utenti value) {
        this.utenti = value;
    }

    /**
     * Gets the value of the personale property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.Personale }
     *     
     */
    public AmministrativaType.Personale getPersonale() {
        return personale;
    }

    /**
     * Sets the value of the personale property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.Personale }
     *     
     */
    public void setPersonale(AmministrativaType.Personale value) {
        this.personale = value;
    }

    /**
     * Gets the value of the bilancio property.
     * 
     * @return
     *     possible object is
     *     {@link AmministrativaType.Bilancio }
     *     
     */
    public AmministrativaType.Bilancio getBilancio() {
        return bilancio;
    }

    /**
     * Sets the value of the bilancio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmministrativaType.Bilancio }
     *     
     */
    public void setBilancio(AmministrativaType.Bilancio value) {
        this.bilancio = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="entrate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="uscite" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="personale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="funzionamento" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="automazione" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="patrimonio" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="altre" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Bilancio {

        protected BigDecimal entrate;
        protected AmministrativaType.Bilancio.Uscite uscite;

        /**
         * Gets the value of the entrate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getEntrate() {
            return entrate;
        }

        /**
         * Sets the value of the entrate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setEntrate(BigDecimal value) {
            this.entrate = value;
        }

        /**
         * Gets the value of the uscite property.
         * 
         * @return
         *     possible object is
         *     {@link AmministrativaType.Bilancio.Uscite }
         *     
         */
        public AmministrativaType.Bilancio.Uscite getUscite() {
            return uscite;
        }

        /**
         * Sets the value of the uscite property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmministrativaType.Bilancio.Uscite }
         *     
         */
        public void setUscite(AmministrativaType.Bilancio.Uscite value) {
            this.uscite = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="personale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="funzionamento" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="automazione" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="patrimonio" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="altre" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Uscite {

            protected BigDecimal totale;
            protected BigDecimal personale;
            protected BigDecimal funzionamento;
            protected BigDecimal automazione;
            protected BigDecimal patrimonio;
            protected BigDecimal altre;

            /**
             * Gets the value of the totale property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotale() {
                return totale;
            }

            /**
             * Sets the value of the totale property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotale(BigDecimal value) {
                this.totale = value;
            }

            /**
             * Gets the value of the personale property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPersonale() {
                return personale;
            }

            /**
             * Sets the value of the personale property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPersonale(BigDecimal value) {
                this.personale = value;
            }

            /**
             * Gets the value of the funzionamento property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getFunzionamento() {
                return funzionamento;
            }

            /**
             * Sets the value of the funzionamento property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setFunzionamento(BigDecimal value) {
                this.funzionamento = value;
            }

            /**
             * Gets the value of the automazione property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAutomazione() {
                return automazione;
            }

            /**
             * Sets the value of the automazione property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAutomazione(BigDecimal value) {
                this.automazione = value;
            }

            /**
             * Gets the value of the patrimonio property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPatrimonio() {
                return patrimonio;
            }

            /**
             * Sets the value of the patrimonio property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPatrimonio(BigDecimal value) {
                this.patrimonio = value;
            }

            /**
             * Gets the value of the altre property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAltre() {
                return altre;
            }

            /**
             * Sets the value of the altre property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAltre(BigDecimal value) {
                this.altre = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="servizio" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "servizio"
    })
    public static class CartaServizi {

        protected List<String> servizio;

        /**
         * Gets the value of the servizio property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the servizio property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getServizio().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getServizio() {
            if (servizio == null) {
                servizio = new ArrayList<String>();
            }
            return this.servizio;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="anno-inizio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipo",
        "annoInizio"
    })
    public static class DepositoLegale {

        protected String tipo;
        @XmlElement(name = "anno-inizio")
        protected String annoInizio;

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the annoInizio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnnoInizio() {
            return annoInizio;
        }

        /**
         * Sets the value of the annoInizio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnnoInizio(String value) {
            this.annoInizio = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tipologia-amministrativa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="tipologia-funzionale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="stato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="codice-fiscale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="partita-IVA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="funzione-obiettivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Ente {

        @XmlElement(required = true)
        protected String nome;
        @XmlElement(name = "tipologia-amministrativa")
        protected String tipologiaAmministrativa;
        @XmlElement(name = "tipologia-funzionale")
        protected String tipologiaFunzionale;
        protected String stato;
        @XmlElement(name = "codice-fiscale")
        protected String codiceFiscale;
        @XmlElement(name = "partita-IVA")
        protected String partitaIVA;
        @XmlElement(name = "funzione-obiettivo")
        protected String funzioneObiettivo;

        /**
         * Gets the value of the nome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNome() {
            return nome;
        }

        /**
         * Sets the value of the nome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNome(String value) {
            this.nome = value;
        }

        /**
         * Gets the value of the tipologiaAmministrativa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipologiaAmministrativa() {
            return tipologiaAmministrativa;
        }

        /**
         * Sets the value of the tipologiaAmministrativa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipologiaAmministrativa(String value) {
            this.tipologiaAmministrativa = value;
        }

        /**
         * Gets the value of the tipologiaFunzionale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipologiaFunzionale() {
            return tipologiaFunzionale;
        }

        /**
         * Sets the value of the tipologiaFunzionale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipologiaFunzionale(String value) {
            this.tipologiaFunzionale = value;
        }

        /**
         * Gets the value of the stato property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStato() {
            return stato;
        }

        /**
         * Sets the value of the stato property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStato(String value) {
            this.stato = value;
        }

        /**
         * Gets the value of the codiceFiscale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodiceFiscale() {
            return codiceFiscale;
        }

        /**
         * Sets the value of the codiceFiscale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodiceFiscale(String value) {
            this.codiceFiscale = value;
        }

        /**
         * Gets the value of the partitaIVA property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartitaIVA() {
            return partitaIVA;
        }

        /**
         * Sets the value of the partitaIVA property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartitaIVA(String value) {
            this.partitaIVA = value;
        }

        /**
         * Gets the value of the funzioneObiettivo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunzioneObiettivo() {
            return funzioneObiettivo;
        }

        /**
         * Sets the value of the funzioneObiettivo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunzioneObiettivo(String value) {
            this.funzioneObiettivo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="temporaneo" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="part-time" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="esterno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Personale {

        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger totale;
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger temporaneo;
        @XmlElement(name = "part-time")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger partTime;
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger esterno;

        /**
         * Gets the value of the totale property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotale() {
            return totale;
        }

        /**
         * Sets the value of the totale property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotale(BigInteger value) {
            this.totale = value;
        }

        /**
         * Gets the value of the temporaneo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTemporaneo() {
            return temporaneo;
        }

        /**
         * Sets the value of the temporaneo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTemporaneo(BigInteger value) {
            this.temporaneo = value;
        }

        /**
         * Gets the value of the partTime property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPartTime() {
            return partTime;
        }

        /**
         * Sets the value of the partTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPartTime(BigInteger value) {
            this.partTime = value;
        }

        /**
         * Gets the value of the esterno property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getEsterno() {
            return esterno;
        }

        /**
         * Sets the value of the esterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setEsterno(BigInteger value) {
            this.esterno = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="norma" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Regolamento {

        protected String norma;
        protected String url;

        /**
         * Gets the value of the norma property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNorma() {
            return norma;
        }

        /**
         * Sets the value of the norma property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNorma(String value) {
            this.norma = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="scaffalature" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="magazzino" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="pubbliche" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="superficie" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="al-pubblico" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="postazioni" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="lettura" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                   &lt;element name="video" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                   &lt;element name="audio" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                   &lt;element name="internet" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Strutture {

        protected AmministrativaType.Strutture.Scaffalature scaffalature;
        protected AmministrativaType.Strutture.Superficie superficie;
        protected AmministrativaType.Strutture.Postazioni postazioni;

        /**
         * Gets the value of the scaffalature property.
         * 
         * @return
         *     possible object is
         *     {@link AmministrativaType.Strutture.Scaffalature }
         *     
         */
        public AmministrativaType.Strutture.Scaffalature getScaffalature() {
            return scaffalature;
        }

        /**
         * Sets the value of the scaffalature property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmministrativaType.Strutture.Scaffalature }
         *     
         */
        public void setScaffalature(AmministrativaType.Strutture.Scaffalature value) {
            this.scaffalature = value;
        }

        /**
         * Gets the value of the superficie property.
         * 
         * @return
         *     possible object is
         *     {@link AmministrativaType.Strutture.Superficie }
         *     
         */
        public AmministrativaType.Strutture.Superficie getSuperficie() {
            return superficie;
        }

        /**
         * Sets the value of the superficie property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmministrativaType.Strutture.Superficie }
         *     
         */
        public void setSuperficie(AmministrativaType.Strutture.Superficie value) {
            this.superficie = value;
        }

        /**
         * Gets the value of the postazioni property.
         * 
         * @return
         *     possible object is
         *     {@link AmministrativaType.Strutture.Postazioni }
         *     
         */
        public AmministrativaType.Strutture.Postazioni getPostazioni() {
            return postazioni;
        }

        /**
         * Sets the value of the postazioni property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmministrativaType.Strutture.Postazioni }
         *     
         */
        public void setPostazioni(AmministrativaType.Strutture.Postazioni value) {
            this.postazioni = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="lettura" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *         &lt;element name="video" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *         &lt;element name="audio" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *         &lt;element name="internet" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Postazioni {

            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger lettura;
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger video;
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger audio;
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger internet;

            /**
             * Gets the value of the lettura property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getLettura() {
                return lettura;
            }

            /**
             * Sets the value of the lettura property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setLettura(BigInteger value) {
                this.lettura = value;
            }

            /**
             * Gets the value of the video property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getVideo() {
                return video;
            }

            /**
             * Sets the value of the video property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setVideo(BigInteger value) {
                this.video = value;
            }

            /**
             * Gets the value of the audio property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAudio() {
                return audio;
            }

            /**
             * Sets the value of the audio property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAudio(BigInteger value) {
                this.audio = value;
            }

            /**
             * Gets the value of the internet property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getInternet() {
                return internet;
            }

            /**
             * Sets the value of the internet property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setInternet(BigInteger value) {
                this.internet = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="magazzino" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="pubbliche" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Scaffalature {

            protected BigDecimal magazzino;
            protected BigDecimal pubbliche;

            /**
             * Gets the value of the magazzino property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMagazzino() {
                return magazzino;
            }

            /**
             * Sets the value of the magazzino property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMagazzino(BigDecimal value) {
                this.magazzino = value;
            }

            /**
             * Gets the value of the pubbliche property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPubbliche() {
                return pubbliche;
            }

            /**
             * Sets the value of the pubbliche property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPubbliche(BigDecimal value) {
                this.pubbliche = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="totale" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="al-pubblico" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Superficie {

            protected BigDecimal totale;
            @XmlElement(name = "al-pubblico")
            protected BigDecimal alPubblico;

            /**
             * Gets the value of the totale property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotale() {
                return totale;
            }

            /**
             * Sets the value of the totale property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotale(BigDecimal value) {
                this.totale = value;
            }

            /**
             * Gets the value of the alPubblico property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAlPubblico() {
                return alPubblico;
            }

            /**
             * Sets the value of the alPubblico property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAlPubblico(BigDecimal value) {
                this.alPubblico = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ultimo-anno" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="iscritti-prestito" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="minori-quattordici-anni" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Utenti {

        @XmlElement(name = "ultimo-anno")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger ultimoAnno;
        @XmlElement(name = "iscritti-prestito")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger iscrittiPrestito;
        @XmlElement(name = "minori-quattordici-anni")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger minoriQuattordiciAnni;

        /**
         * Gets the value of the ultimoAnno property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUltimoAnno() {
            return ultimoAnno;
        }

        /**
         * Sets the value of the ultimoAnno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUltimoAnno(BigInteger value) {
            this.ultimoAnno = value;
        }

        /**
         * Gets the value of the iscrittiPrestito property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIscrittiPrestito() {
            return iscrittiPrestito;
        }

        /**
         * Sets the value of the iscrittiPrestito property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIscrittiPrestito(BigInteger value) {
            this.iscrittiPrestito = value;
        }

        /**
         * Gets the value of the minoriQuattordiciAnni property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMinoriQuattordiciAnni() {
            return minoriQuattordiciAnni;
        }

        /**
         * Sets the value of the minoriQuattordiciAnni property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMinoriQuattordiciAnni(BigInteger value) {
            this.minoriQuattordiciAnni = value;
        }

    }

}
