//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package xml.xsd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				Questo tipo raggruppa tutte le informazioni di tipo
 * 				strettamente anagrafico.
 * 			
 * 
 * <p>Java class for anagraficaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anagraficaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="dataCensimento" type="{}annoSecoloType" minOccurs="0"/>
 *         &lt;element name="dataAggiornamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="nome">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attuale">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="precedente" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="alternativo" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="codici">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="iccu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="acnp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="rism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cei" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cmbs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="indirizzo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="via" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="frazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="comune" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{6}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="provincia" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{3}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="regione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="stato" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contatti" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="telefonico" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                           &lt;attribute name="tipo" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="fax"/>
 *                                 &lt;enumeration value="telefono"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="altro" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="tipo" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="e-mail"/>
 *                                 &lt;enumeration value="telex"/>
 *                                 &lt;enumeration value="url"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="edificio" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="denominazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="monumentale" type="{}siNoType" minOccurs="0"/>
 *                   &lt;element name="appositamenteCostruito" type="{}siNoType" minOccurs="0"/>
 *                   &lt;element name="dataCostruzione" type="{}annoSecoloType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Istituzione" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataIstituzione" type="{}annoSecoloType" minOccurs="0"/>
 *                   &lt;element name="dataFondazione" type="{}annoSecoloType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anagraficaType", propOrder = {

})
public class AnagraficaType {

    protected AnnoSecoloType dataCensimento;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataAggiornamento;
    @XmlElement(required = true)
    protected AnagraficaType.Nome nome;
    @XmlElement(required = true)
    protected AnagraficaType.Codici codici;
    protected AnagraficaType.Indirizzo indirizzo;
    protected AnagraficaType.Contatti contatti;
    protected AnagraficaType.Edificio edificio;
    @XmlElement(name = "Istituzione")
    protected AnagraficaType.Istituzione istituzione;

    /**
     * Gets the value of the dataCensimento property.
     * 
     * @return
     *     possible object is
     *     {@link AnnoSecoloType }
     *     
     */
    public AnnoSecoloType getDataCensimento() {
        return dataCensimento;
    }

    /**
     * Sets the value of the dataCensimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnoSecoloType }
     *     
     */
    public void setDataCensimento(AnnoSecoloType value) {
        this.dataCensimento = value;
    }

    /**
     * Gets the value of the dataAggiornamento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * Sets the value of the dataAggiornamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAggiornamento(XMLGregorianCalendar value) {
        this.dataAggiornamento = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Nome }
     *     
     */
    public AnagraficaType.Nome getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Nome }
     *     
     */
    public void setNome(AnagraficaType.Nome value) {
        this.nome = value;
    }

    /**
     * Gets the value of the codici property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Codici }
     *     
     */
    public AnagraficaType.Codici getCodici() {
        return codici;
    }

    /**
     * Sets the value of the codici property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Codici }
     *     
     */
    public void setCodici(AnagraficaType.Codici value) {
        this.codici = value;
    }

    /**
     * Gets the value of the indirizzo property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Indirizzo }
     *     
     */
    public AnagraficaType.Indirizzo getIndirizzo() {
        return indirizzo;
    }

    /**
     * Sets the value of the indirizzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Indirizzo }
     *     
     */
    public void setIndirizzo(AnagraficaType.Indirizzo value) {
        this.indirizzo = value;
    }

    /**
     * Gets the value of the contatti property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Contatti }
     *     
     */
    public AnagraficaType.Contatti getContatti() {
        return contatti;
    }

    /**
     * Sets the value of the contatti property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Contatti }
     *     
     */
    public void setContatti(AnagraficaType.Contatti value) {
        this.contatti = value;
    }

    /**
     * Gets the value of the edificio property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Edificio }
     *     
     */
    public AnagraficaType.Edificio getEdificio() {
        return edificio;
    }

    /**
     * Sets the value of the edificio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Edificio }
     *     
     */
    public void setEdificio(AnagraficaType.Edificio value) {
        this.edificio = value;
    }

    /**
     * Gets the value of the istituzione property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Istituzione }
     *     
     */
    public AnagraficaType.Istituzione getIstituzione() {
        return istituzione;
    }

    /**
     * Sets the value of the istituzione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Istituzione }
     *     
     */
    public void setIstituzione(AnagraficaType.Istituzione value) {
        this.istituzione = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="iccu" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="acnp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="rism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cei" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cmbs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Codici {

        @XmlElement(required = true)
        protected String iccu;
        protected String acnp;
        protected String rism;
        protected String sbn;
        protected String cei;
        protected String cmbs;

        /**
         * Gets the value of the iccu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIccu() {
            return iccu;
        }

        /**
         * Sets the value of the iccu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIccu(String value) {
            this.iccu = value;
        }

        /**
         * Gets the value of the acnp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcnp() {
            return acnp;
        }

        /**
         * Sets the value of the acnp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcnp(String value) {
            this.acnp = value;
        }

        /**
         * Gets the value of the rism property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRism() {
            return rism;
        }

        /**
         * Sets the value of the rism property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRism(String value) {
            this.rism = value;
        }

        /**
         * Gets the value of the sbn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSbn() {
            return sbn;
        }

        /**
         * Sets the value of the sbn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSbn(String value) {
            this.sbn = value;
        }

        /**
         * Gets the value of the cei property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCei() {
            return cei;
        }

        /**
         * Sets the value of the cei property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCei(String value) {
            this.cei = value;
        }

        /**
         * Gets the value of the cmbs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCmbs() {
            return cmbs;
        }

        /**
         * Sets the value of the cmbs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCmbs(String value) {
            this.cmbs = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="telefonico" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *                 &lt;attribute name="tipo" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="fax"/>
     *                       &lt;enumeration value="telefono"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="altro" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="tipo" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="e-mail"/>
     *                       &lt;enumeration value="telex"/>
     *                       &lt;enumeration value="url"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "telefonico",
        "altro"
    })
    public static class Contatti {

        protected List<AnagraficaType.Contatti.Telefonico> telefonico;
        protected List<AnagraficaType.Contatti.Altro> altro;

        /**
         * Gets the value of the telefonico property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the telefonico property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTelefonico().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnagraficaType.Contatti.Telefonico }
         * 
         * 
         */
        public List<AnagraficaType.Contatti.Telefonico> getTelefonico() {
            if (telefonico == null) {
                telefonico = new ArrayList<AnagraficaType.Contatti.Telefonico>();
            }
            return this.telefonico;
        }

        /**
         * Gets the value of the altro property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the altro property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAltro().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnagraficaType.Contatti.Altro }
         * 
         * 
         */
        public List<AnagraficaType.Contatti.Altro> getAltro() {
            if (altro == null) {
                altro = new ArrayList<AnagraficaType.Contatti.Altro>();
            }
            return this.altro;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="tipo" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="e-mail"/>
         *             &lt;enumeration value="telex"/>
         *             &lt;enumeration value="url"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "valore",
            "note"
        })
        public static class Altro {

            @XmlElement(required = true)
            protected String valore;
            protected String note;
            @XmlAttribute(required = true)
            protected String tipo;

            /**
             * Gets the value of the valore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValore() {
                return valore;
            }

            /**
             * Sets the value of the valore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValore(String value) {
                this.valore = value;
            }

            /**
             * Gets the value of the note property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNote() {
                return note;
            }

            /**
             * Sets the value of the note property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNote(String value) {
                this.note = value;
            }

            /**
             * Gets the value of the tipo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipo() {
                return tipo;
            }

            /**
             * Sets the value of the tipo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipo(String value) {
                this.tipo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *       &lt;attribute name="tipo" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="fax"/>
         *             &lt;enumeration value="telefono"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Telefonico {

            @XmlElement(required = true)
            protected String prefisso;
            @XmlElement(required = true)
            protected String numero;
            protected String note;
            @XmlAttribute(required = true)
            protected String tipo;

            /**
             * Gets the value of the prefisso property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrefisso() {
                return prefisso;
            }

            /**
             * Sets the value of the prefisso property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrefisso(String value) {
                this.prefisso = value;
            }

            /**
             * Gets the value of the numero property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumero() {
                return numero;
            }

            /**
             * Sets the value of the numero property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumero(String value) {
                this.numero = value;
            }

            /**
             * Gets the value of the note property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNote() {
                return note;
            }

            /**
             * Sets the value of the note property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNote(String value) {
                this.note = value;
            }

            /**
             * Gets the value of the tipo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipo() {
                return tipo;
            }

            /**
             * Sets the value of the tipo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipo(String value) {
                this.tipo = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="denominazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="monumentale" type="{}siNoType" minOccurs="0"/>
     *         &lt;element name="appositamenteCostruito" type="{}siNoType" minOccurs="0"/>
     *         &lt;element name="dataCostruzione" type="{}annoSecoloType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "denominazione",
        "monumentale",
        "appositamenteCostruito",
        "dataCostruzione"
    })
    public static class Edificio {

        protected String denominazione;
        protected SiNoType monumentale;
        protected SiNoType appositamenteCostruito;
        protected AnnoSecoloType dataCostruzione;

        /**
         * Gets the value of the denominazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenominazione() {
            return denominazione;
        }

        /**
         * Sets the value of the denominazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenominazione(String value) {
            this.denominazione = value;
        }

        /**
         * Gets the value of the monumentale property.
         * 
         * @return
         *     possible object is
         *     {@link SiNoType }
         *     
         */
        public SiNoType getMonumentale() {
            return monumentale;
        }

        /**
         * Sets the value of the monumentale property.
         * 
         * @param value
         *     allowed object is
         *     {@link SiNoType }
         *     
         */
        public void setMonumentale(SiNoType value) {
            this.monumentale = value;
        }

        /**
         * Gets the value of the appositamenteCostruito property.
         * 
         * @return
         *     possible object is
         *     {@link SiNoType }
         *     
         */
        public SiNoType getAppositamenteCostruito() {
            return appositamenteCostruito;
        }

        /**
         * Sets the value of the appositamenteCostruito property.
         * 
         * @param value
         *     allowed object is
         *     {@link SiNoType }
         *     
         */
        public void setAppositamenteCostruito(SiNoType value) {
            this.appositamenteCostruito = value;
        }

        /**
         * Gets the value of the dataCostruzione property.
         * 
         * @return
         *     possible object is
         *     {@link AnnoSecoloType }
         *     
         */
        public AnnoSecoloType getDataCostruzione() {
            return dataCostruzione;
        }

        /**
         * Sets the value of the dataCostruzione property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnoSecoloType }
         *     
         */
        public void setDataCostruzione(AnnoSecoloType value) {
            this.dataCostruzione = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="via" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="frazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="comune" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{6}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="provincia" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{3}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="regione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="stato" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[a-zA-Z]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Indirizzo {

        protected String via;
        protected String cap;
        protected String frazione;
        protected String comune;
        protected String provincia;
        protected String regione;
        protected String stato;

        /**
         * Gets the value of the via property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVia() {
            return via;
        }

        /**
         * Sets the value of the via property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVia(String value) {
            this.via = value;
        }

        /**
         * Gets the value of the cap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCap() {
            return cap;
        }

        /**
         * Sets the value of the cap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCap(String value) {
            this.cap = value;
        }

        /**
         * Gets the value of the frazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrazione() {
            return frazione;
        }

        /**
         * Sets the value of the frazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrazione(String value) {
            this.frazione = value;
        }

        /**
         * Gets the value of the comune property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComune() {
            return comune;
        }

        /**
         * Sets the value of the comune property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComune(String value) {
            this.comune = value;
        }

        /**
         * Gets the value of the provincia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProvincia() {
            return provincia;
        }

        /**
         * Sets the value of the provincia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProvincia(String value) {
            this.provincia = value;
        }

        /**
         * Gets the value of the regione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegione() {
            return regione;
        }

        /**
         * Sets the value of the regione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegione(String value) {
            this.regione = value;
        }

        /**
         * Gets the value of the stato property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStato() {
            return stato;
        }

        /**
         * Sets the value of the stato property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStato(String value) {
            this.stato = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataIstituzione" type="{}annoSecoloType" minOccurs="0"/>
     *         &lt;element name="dataFondazione" type="{}annoSecoloType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataIstituzione",
        "dataFondazione"
    })
    public static class Istituzione {

        protected AnnoSecoloType dataIstituzione;
        protected AnnoSecoloType dataFondazione;

        /**
         * Gets the value of the dataIstituzione property.
         * 
         * @return
         *     possible object is
         *     {@link AnnoSecoloType }
         *     
         */
        public AnnoSecoloType getDataIstituzione() {
            return dataIstituzione;
        }

        /**
         * Sets the value of the dataIstituzione property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnoSecoloType }
         *     
         */
        public void setDataIstituzione(AnnoSecoloType value) {
            this.dataIstituzione = value;
        }

        /**
         * Gets the value of the dataFondazione property.
         * 
         * @return
         *     possible object is
         *     {@link AnnoSecoloType }
         *     
         */
        public AnnoSecoloType getDataFondazione() {
            return dataFondazione;
        }

        /**
         * Sets the value of the dataFondazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnoSecoloType }
         *     
         */
        public void setDataFondazione(AnnoSecoloType value) {
            this.dataFondazione = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attuale">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="precedente" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="alternativo" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attuale",
        "precedente",
        "alternativo"
    })
    public static class Nome {

        @XmlElement(required = true)
        protected String attuale;
        protected List<String> precedente;
        protected List<String> alternativo;

        /**
         * Gets the value of the attuale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttuale() {
            return attuale;
        }

        /**
         * Sets the value of the attuale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttuale(String value) {
            this.attuale = value;
        }

        /**
         * Gets the value of the precedente property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the precedente property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrecedente().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPrecedente() {
            if (precedente == null) {
                precedente = new ArrayList<String>();
            }
            return this.precedente;
        }

        /**
         * Gets the value of the alternativo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the alternativo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAlternativo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAlternativo() {
            if (alternativo == null) {
                alternativo = new ArrayList<String>();
            }
            return this.alternativo;
        }

    }

}
