//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package it.sbn.iccu.abi.xml.xsd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Tutti i tre sotto-elementi sono opzionali e ripetibili
 * 				in un ordine qualsiasi. Nel definire i tre sottotipi
 * 				sono sfruttate dove possibile le somiglianze fra i tre,
 * 				attraverso la derivazione di un tipo da un altro.
 * 			
 * 
 * <p>Java class for cataloghiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cataloghiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="catalogo-generale" type="{}catalogoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="catalogo-speciale" type="{}catalogoSpecialeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="catalogo-collettivo" type="{}catalogoCollettivoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cataloghiType", propOrder = {
    "catalogoGenerale",
    "catalogoSpeciale",
    "catalogoCollettivo"
})
public class CataloghiType {

    @XmlElement(name = "catalogo-generale")
    protected List<CatalogoType> catalogoGenerale;
    @XmlElement(name = "catalogo-speciale")
    protected List<CatalogoSpecialeType> catalogoSpeciale;
    @XmlElement(name = "catalogo-collettivo")
    protected List<CatalogoCollettivoType> catalogoCollettivo;

    /**
     * Gets the value of the catalogoGenerale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catalogoGenerale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatalogoGenerale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CatalogoType }
     * 
     * 
     */
    public List<CatalogoType> getCatalogoGenerale() {
        if (catalogoGenerale == null) {
            catalogoGenerale = new ArrayList<CatalogoType>();
        }
        return this.catalogoGenerale;
    }

    /**
     * Gets the value of the catalogoSpeciale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catalogoSpeciale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatalogoSpeciale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CatalogoSpecialeType }
     * 
     * 
     */
    public List<CatalogoSpecialeType> getCatalogoSpeciale() {
        if (catalogoSpeciale == null) {
            catalogoSpeciale = new ArrayList<CatalogoSpecialeType>();
        }
        return this.catalogoSpeciale;
    }

    /**
     * Gets the value of the catalogoCollettivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the catalogoCollettivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCatalogoCollettivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CatalogoCollettivoType }
     * 
     * 
     */
    public List<CatalogoCollettivoType> getCatalogoCollettivo() {
        if (catalogoCollettivo == null) {
            catalogoCollettivo = new ArrayList<CatalogoCollettivoType>();
        }
        return this.catalogoCollettivo;
    }

}
