//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package it.sbn.iccu.abi.xml.xsd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Per i limiti orari si potrebbe specificare un vincolo
 * 				più fine, perché quello attuale accetterebbe anche un
 * 				orario come "35:72".
 * 			
 * 
 * <p>Java class for orarioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orarioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orario" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="giorno" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="lun"/>
 *                       &lt;enumeration value="mar"/>
 *                       &lt;enumeration value="mer"/>
 *                       &lt;enumeration value="gio"/>
 *                       &lt;enumeration value="ven"/>
 *                       &lt;enumeration value="sab"/>
 *                       &lt;enumeration value="dom"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="dalle" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="[0-9]{2}:[0-9]{2}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="alle" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="[0-9]{2}:[0-9]{2}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orarioType", propOrder = {
    "orario"
})
@XmlSeeAlso({
    it.sbn.iccu.abi.xml.xsd.ServiziType.Orario.Variazione.class
})
public class OrarioType {

    @XmlElement(required = true)
    protected List<OrarioType.Orario> orario;

    /**
     * Gets the value of the orario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrarioType.Orario }
     * 
     * 
     */
    public List<OrarioType.Orario> getOrario() {
        if (orario == null) {
            orario = new ArrayList<OrarioType.Orario>();
        }
        return this.orario;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="giorno" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="lun"/>
     *             &lt;enumeration value="mar"/>
     *             &lt;enumeration value="mer"/>
     *             &lt;enumeration value="gio"/>
     *             &lt;enumeration value="ven"/>
     *             &lt;enumeration value="sab"/>
     *             &lt;enumeration value="dom"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="dalle" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="[0-9]{2}:[0-9]{2}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="alle" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="[0-9]{2}:[0-9]{2}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Orario {

        @XmlAttribute(required = true)
        protected String giorno;
        @XmlAttribute(required = true)
        protected String dalle;
        @XmlAttribute(required = true)
        protected String alle;

        /**
         * Gets the value of the giorno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiorno() {
            return giorno;
        }

        /**
         * Sets the value of the giorno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiorno(String value) {
            this.giorno = value;
        }

        /**
         * Gets the value of the dalle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDalle() {
            return dalle;
        }

        /**
         * Sets the value of the dalle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDalle(String value) {
            this.dalle = value;
        }

        /**
         * Gets the value of the alle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlle() {
            return alle;
        }

        /**
         * Sets the value of the alle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlle(String value) {
            this.alle = value;
        }

    }

}
