//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package it.sbn.iccu.abi.xml.xsd;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Tipo di elemento relativo ai servizi offerti da una
 * 				biblioteca. Fra questi, gli orari di apertura, il
 * 				prestito, le informazioni bibliografiche, tipo e
 * 				condizioni di accesso e diverse altre informazioni.
 * 			
 * 
 * <p>Java class for serviziType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serviziType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orario" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ufficiale" type="{}orarioType" minOccurs="0"/>
 *                   &lt;element name="variazione" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}orarioType">
 *                           &lt;sequence>
 *                             &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="chiusura" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ore-settimanali" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="ore-settimanali-pomeridiane" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="settimane-apertura" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="prestito" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="locale" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="automatizzato" type="{}siNoType" minOccurs="0"/>
 *                             &lt;element name="materiale-escluso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="durata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="utenti-ammessi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="totale-prestiti" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="interbibliotecario" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tipo-prestito" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
 *                                       &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
 *                                       &lt;element name="ruolo">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="POS"/>
 *                                             &lt;enumeration value="DSC"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="automatizzato" type="{}siNoType" minOccurs="0"/>
 *                             &lt;element name="totale-prestiti" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="sistema-ill" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="materiali-esclusi-locale" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="materiale" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="riproduzioni" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="locale" type="{}siNoType" minOccurs="0"/>
 *                             &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
 *                             &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informazioni-bibliografiche">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="servizio-interno" type="{}siNoType" minOccurs="0"/>
 *                   &lt;element name="servizio-esterno" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="modo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="internet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="modo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="accesso" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="aperta" type="{}siNoType" minOccurs="0"/>
 *                   &lt;element name="handicap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="categoria-ammessa" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="condizioni-accesso" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="eta" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                                     &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="documenti" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="appuntamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="destinazioni-sociali" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="destinazione" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sistemi" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="sistema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sezioni-speciali" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sezione" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviziType", propOrder = {
    "orario",
    "prestito",
    "informazioniBibliografiche",
    "internet",
    "accesso",
    "sistemi",
    "sezioniSpeciali"
})
public class ServiziType {

    protected ServiziType.Orario orario;
    protected ServiziType.Prestito prestito;
    @XmlElement(name = "informazioni-bibliografiche", required = true)
    protected ServiziType.InformazioniBibliografiche informazioniBibliografiche;
    @XmlElement(required = true)
    protected ServiziType.Internet internet;
    protected ServiziType.Accesso accesso;
    protected List<ServiziType.Sistemi> sistemi;
    @XmlElement(name = "sezioni-speciali")
    protected ServiziType.SezioniSpeciali sezioniSpeciali;

    /**
     * Gets the value of the orario property.
     * 
     * @return
     *     possible object is
     *     {@link ServiziType.Orario }
     *     
     */
    public ServiziType.Orario getOrario() {
        return orario;
    }

    /**
     * Sets the value of the orario property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiziType.Orario }
     *     
     */
    public void setOrario(ServiziType.Orario value) {
        this.orario = value;
    }

    /**
     * Gets the value of the prestito property.
     * 
     * @return
     *     possible object is
     *     {@link ServiziType.Prestito }
     *     
     */
    public ServiziType.Prestito getPrestito() {
        return prestito;
    }

    /**
     * Sets the value of the prestito property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiziType.Prestito }
     *     
     */
    public void setPrestito(ServiziType.Prestito value) {
        this.prestito = value;
    }

    /**
     * Gets the value of the informazioniBibliografiche property.
     * 
     * @return
     *     possible object is
     *     {@link ServiziType.InformazioniBibliografiche }
     *     
     */
    public ServiziType.InformazioniBibliografiche getInformazioniBibliografiche() {
        return informazioniBibliografiche;
    }

    /**
     * Sets the value of the informazioniBibliografiche property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiziType.InformazioniBibliografiche }
     *     
     */
    public void setInformazioniBibliografiche(ServiziType.InformazioniBibliografiche value) {
        this.informazioniBibliografiche = value;
    }

    /**
     * Gets the value of the internet property.
     * 
     * @return
     *     possible object is
     *     {@link ServiziType.Internet }
     *     
     */
    public ServiziType.Internet getInternet() {
        return internet;
    }

    /**
     * Sets the value of the internet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiziType.Internet }
     *     
     */
    public void setInternet(ServiziType.Internet value) {
        this.internet = value;
    }

    /**
     * Gets the value of the accesso property.
     * 
     * @return
     *     possible object is
     *     {@link ServiziType.Accesso }
     *     
     */
    public ServiziType.Accesso getAccesso() {
        return accesso;
    }

    /**
     * Sets the value of the accesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiziType.Accesso }
     *     
     */
    public void setAccesso(ServiziType.Accesso value) {
        this.accesso = value;
    }

    /**
     * Gets the value of the sistemi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sistemi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSistemi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiziType.Sistemi }
     * 
     * 
     */
    public List<ServiziType.Sistemi> getSistemi() {
        if (sistemi == null) {
            sistemi = new ArrayList<ServiziType.Sistemi>();
        }
        return this.sistemi;
    }

    /**
     * Gets the value of the sezioniSpeciali property.
     * 
     * @return
     *     possible object is
     *     {@link ServiziType.SezioniSpeciali }
     *     
     */
    public ServiziType.SezioniSpeciali getSezioniSpeciali() {
        return sezioniSpeciali;
    }

    /**
     * Sets the value of the sezioniSpeciali property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiziType.SezioniSpeciali }
     *     
     */
    public void setSezioniSpeciali(ServiziType.SezioniSpeciali value) {
        this.sezioniSpeciali = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="aperta" type="{}siNoType" minOccurs="0"/>
     *         &lt;element name="handicap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="categoria-ammessa" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="condizioni-accesso" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="eta" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                           &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="documenti" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="appuntamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="destinazioni-sociali" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="destinazione" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aperta",
        "handicap",
        "categoriaAmmessa",
        "condizioniAccesso",
        "destinazioniSociali"
    })
    public static class Accesso {

        protected SiNoType aperta;
        protected String handicap;
        @XmlElement(name = "categoria-ammessa")
        protected List<String> categoriaAmmessa;
        @XmlElement(name = "condizioni-accesso")
        protected List<ServiziType.Accesso.CondizioniAccesso> condizioniAccesso;
        @XmlElement(name = "destinazioni-sociali")
        protected ServiziType.Accesso.DestinazioniSociali destinazioniSociali;

        /**
         * Gets the value of the aperta property.
         * 
         * @return
         *     possible object is
         *     {@link SiNoType }
         *     
         */
        public SiNoType getAperta() {
            return aperta;
        }

        /**
         * Sets the value of the aperta property.
         * 
         * @param value
         *     allowed object is
         *     {@link SiNoType }
         *     
         */
        public void setAperta(SiNoType value) {
            this.aperta = value;
        }

        /**
         * Gets the value of the handicap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHandicap() {
            return handicap;
        }

        /**
         * Sets the value of the handicap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHandicap(String value) {
            this.handicap = value;
        }

        /**
         * Gets the value of the categoriaAmmessa property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the categoriaAmmessa property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCategoriaAmmessa().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCategoriaAmmessa() {
            if (categoriaAmmessa == null) {
                categoriaAmmessa = new ArrayList<String>();
            }
            return this.categoriaAmmessa;
        }

        /**
         * Gets the value of the condizioniAccesso property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the condizioniAccesso property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCondizioniAccesso().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiziType.Accesso.CondizioniAccesso }
         * 
         * 
         */
        public List<ServiziType.Accesso.CondizioniAccesso> getCondizioniAccesso() {
            if (condizioniAccesso == null) {
                condizioniAccesso = new ArrayList<ServiziType.Accesso.CondizioniAccesso>();
            }
            return this.condizioniAccesso;
        }

        /**
         * Gets the value of the destinazioniSociali property.
         * 
         * @return
         *     possible object is
         *     {@link ServiziType.Accesso.DestinazioniSociali }
         *     
         */
        public ServiziType.Accesso.DestinazioniSociali getDestinazioniSociali() {
            return destinazioniSociali;
        }

        /**
         * Sets the value of the destinazioniSociali property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiziType.Accesso.DestinazioniSociali }
         *     
         */
        public void setDestinazioniSociali(ServiziType.Accesso.DestinazioniSociali value) {
            this.destinazioniSociali = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="eta" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="documenti" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="appuntamento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class CondizioniAccesso {

            protected ServiziType.Accesso.CondizioniAccesso.Eta eta;
            protected ServiziType.Accesso.CondizioniAccesso.Documenti documenti;
            protected String appuntamento;

            /**
             * Gets the value of the eta property.
             * 
             * @return
             *     possible object is
             *     {@link ServiziType.Accesso.CondizioniAccesso.Eta }
             *     
             */
            public ServiziType.Accesso.CondizioniAccesso.Eta getEta() {
                return eta;
            }

            /**
             * Sets the value of the eta property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiziType.Accesso.CondizioniAccesso.Eta }
             *     
             */
            public void setEta(ServiziType.Accesso.CondizioniAccesso.Eta value) {
                this.eta = value;
            }

            /**
             * Gets the value of the documenti property.
             * 
             * @return
             *     possible object is
             *     {@link ServiziType.Accesso.CondizioniAccesso.Documenti }
             *     
             */
            public ServiziType.Accesso.CondizioniAccesso.Documenti getDocumenti() {
                return documenti;
            }

            /**
             * Sets the value of the documenti property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiziType.Accesso.CondizioniAccesso.Documenti }
             *     
             */
            public void setDocumenti(ServiziType.Accesso.CondizioniAccesso.Documenti value) {
                this.documenti = value;
            }

            /**
             * Gets the value of the appuntamento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAppuntamento() {
                return appuntamento;
            }

            /**
             * Sets the value of the appuntamento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAppuntamento(String value) {
                this.appuntamento = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tipo"
            })
            public static class Documenti {

                protected List<String> tipo;

                /**
                 * Gets the value of the tipo property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the tipo property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTipo().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getTipo() {
                    if (tipo == null) {
                        tipo = new ArrayList<String>();
                    }
                    return this.tipo;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
             *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Eta {

                @XmlAttribute
                @XmlSchemaType(name = "nonNegativeInteger")
                protected BigInteger min;
                @XmlAttribute
                @XmlSchemaType(name = "nonNegativeInteger")
                protected BigInteger max;

                /**
                 * Gets the value of the min property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMin() {
                    return min;
                }

                /**
                 * Sets the value of the min property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMin(BigInteger value) {
                    this.min = value;
                }

                /**
                 * Gets the value of the max property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMax() {
                    return max;
                }

                /**
                 * Sets the value of the max property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMax(BigInteger value) {
                    this.max = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="destinazione" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "destinazione"
        })
        public static class DestinazioniSociali {

            @XmlElement(required = true)
            protected List<ServiziType.Accesso.DestinazioniSociali.Destinazione> destinazione;

            /**
             * Gets the value of the destinazione property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the destinazione property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDestinazione().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ServiziType.Accesso.DestinazioniSociali.Destinazione }
             * 
             * 
             */
            public List<ServiziType.Accesso.DestinazioniSociali.Destinazione> getDestinazione() {
                if (destinazione == null) {
                    destinazione = new ArrayList<ServiziType.Accesso.DestinazioniSociali.Destinazione>();
                }
                return this.destinazione;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "valore",
                "note"
            })
            public static class Destinazione {

                @XmlElement(required = true)
                protected String valore;
                protected String note;

                /**
                 * Gets the value of the valore property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValore() {
                    return valore;
                }

                /**
                 * Sets the value of the valore property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValore(String value) {
                    this.valore = value;
                }

                /**
                 * Gets the value of the note property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNote() {
                    return note;
                }

                /**
                 * Sets the value of the note property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNote(String value) {
                    this.note = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="servizio-interno" type="{}siNoType" minOccurs="0"/>
     *         &lt;element name="servizio-esterno" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="modo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class InformazioniBibliografiche {

        @XmlElement(name = "servizio-interno")
        protected SiNoType servizioInterno;
        @XmlElement(name = "servizio-esterno")
        protected ServiziType.InformazioniBibliografiche.ServizioEsterno servizioEsterno;

        /**
         * Gets the value of the servizioInterno property.
         * 
         * @return
         *     possible object is
         *     {@link SiNoType }
         *     
         */
        public SiNoType getServizioInterno() {
            return servizioInterno;
        }

        /**
         * Sets the value of the servizioInterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link SiNoType }
         *     
         */
        public void setServizioInterno(SiNoType value) {
            this.servizioInterno = value;
        }

        /**
         * Gets the value of the servizioEsterno property.
         * 
         * @return
         *     possible object is
         *     {@link ServiziType.InformazioniBibliografiche.ServizioEsterno }
         *     
         */
        public ServiziType.InformazioniBibliografiche.ServizioEsterno getServizioEsterno() {
            return servizioEsterno;
        }

        /**
         * Sets the value of the servizioEsterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiziType.InformazioniBibliografiche.ServizioEsterno }
         *     
         */
        public void setServizioEsterno(ServiziType.InformazioniBibliografiche.ServizioEsterno value) {
            this.servizioEsterno = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="modo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "modo"
        })
        public static class ServizioEsterno {

            protected List<String> modo;

            /**
             * Gets the value of the modo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the modo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getModo().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getModo() {
                if (modo == null) {
                    modo = new ArrayList<String>();
                }
                return this.modo;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="modo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "modo"
    })
    public static class Internet {

        protected String modo;

        /**
         * Gets the value of the modo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModo() {
            return modo;
        }

        /**
         * Sets the value of the modo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModo(String value) {
            this.modo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ufficiale" type="{}orarioType" minOccurs="0"/>
     *         &lt;element name="variazione" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}orarioType">
     *                 &lt;sequence>
     *                   &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="chiusura" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ore-settimanali" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="ore-settimanali-pomeridiane" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="settimane-apertura" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ufficiale",
        "variazione",
        "chiusura",
        "oreSettimanali",
        "oreSettimanaliPomeridiane",
        "settimaneApertura"
    })
    public static class Orario {

        protected OrarioType ufficiale;
        protected List<ServiziType.Orario.Variazione> variazione;
        protected List<ServiziType.Orario.Chiusura> chiusura;
        @XmlElement(name = "ore-settimanali")
        protected BigDecimal oreSettimanali;
        @XmlElement(name = "ore-settimanali-pomeridiane")
        protected BigDecimal oreSettimanaliPomeridiane;
        @XmlElement(name = "settimane-apertura")
        protected BigDecimal settimaneApertura;

        /**
         * Gets the value of the ufficiale property.
         * 
         * @return
         *     possible object is
         *     {@link OrarioType }
         *     
         */
        public OrarioType getUfficiale() {
            return ufficiale;
        }

        /**
         * Sets the value of the ufficiale property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrarioType }
         *     
         */
        public void setUfficiale(OrarioType value) {
            this.ufficiale = value;
        }

        /**
         * Gets the value of the variazione property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the variazione property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVariazione().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiziType.Orario.Variazione }
         * 
         * 
         */
        public List<ServiziType.Orario.Variazione> getVariazione() {
            if (variazione == null) {
                variazione = new ArrayList<ServiziType.Orario.Variazione>();
            }
            return this.variazione;
        }

        /**
         * Gets the value of the chiusura property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the chiusura property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChiusura().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiziType.Orario.Chiusura }
         * 
         * 
         */
        public List<ServiziType.Orario.Chiusura> getChiusura() {
            if (chiusura == null) {
                chiusura = new ArrayList<ServiziType.Orario.Chiusura>();
            }
            return this.chiusura;
        }

        /**
         * Gets the value of the oreSettimanali property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOreSettimanali() {
            return oreSettimanali;
        }

        /**
         * Sets the value of the oreSettimanali property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOreSettimanali(BigDecimal value) {
            this.oreSettimanali = value;
        }

        /**
         * Gets the value of the oreSettimanaliPomeridiane property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOreSettimanaliPomeridiane() {
            return oreSettimanaliPomeridiane;
        }

        /**
         * Sets the value of the oreSettimanaliPomeridiane property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOreSettimanaliPomeridiane(BigDecimal value) {
            this.oreSettimanaliPomeridiane = value;
        }

        /**
         * Gets the value of the settimaneApertura property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSettimaneApertura() {
            return settimaneApertura;
        }

        /**
         * Sets the value of the settimaneApertura property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSettimaneApertura(BigDecimal value) {
            this.settimaneApertura = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Chiusura {

            protected String periodo;
            @XmlElement(required = true)
            protected String note;

            /**
             * Gets the value of the periodo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPeriodo() {
                return periodo;
            }

            /**
             * Sets the value of the periodo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPeriodo(String value) {
                this.periodo = value;
            }

            /**
             * Gets the value of the note property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNote() {
                return note;
            }

            /**
             * Sets the value of the note property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNote(String value) {
                this.note = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}orarioType">
         *       &lt;sequence>
         *         &lt;element name="periodo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "periodo",
            "note"
        })
        public static class Variazione
            extends OrarioType
        {

            protected String periodo;
            @XmlElement(required = true)
            protected String note;

            /**
             * Gets the value of the periodo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPeriodo() {
                return periodo;
            }

            /**
             * Sets the value of the periodo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPeriodo(String value) {
                this.periodo = value;
            }

            /**
             * Gets the value of the note property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNote() {
                return note;
            }

            /**
             * Sets the value of the note property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNote(String value) {
                this.note = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="locale" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="automatizzato" type="{}siNoType" minOccurs="0"/>
     *                   &lt;element name="materiale-escluso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="durata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="utenti-ammessi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="totale-prestiti" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="interbibliotecario" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tipo-prestito" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
     *                             &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
     *                             &lt;element name="ruolo">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;enumeration value="POS"/>
     *                                   &lt;enumeration value="DSC"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="automatizzato" type="{}siNoType" minOccurs="0"/>
     *                   &lt;element name="totale-prestiti" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="sistema-ill" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="materiali-esclusi-locale" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="materiale" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="riproduzioni" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="locale" type="{}siNoType" minOccurs="0"/>
     *                   &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
     *                   &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "locale",
        "interbibliotecario",
        "materialiEsclusiLocale",
        "riproduzioni"
    })
    public static class Prestito {

        protected ServiziType.Prestito.Locale locale;
        protected ServiziType.Prestito.Interbibliotecario interbibliotecario;
        @XmlElement(name = "materiali-esclusi-locale")
        protected ServiziType.Prestito.MaterialiEsclusiLocale materialiEsclusiLocale;
        protected List<ServiziType.Prestito.Riproduzioni> riproduzioni;

        /**
         * Gets the value of the locale property.
         * 
         * @return
         *     possible object is
         *     {@link ServiziType.Prestito.Locale }
         *     
         */
        public ServiziType.Prestito.Locale getLocale() {
            return locale;
        }

        /**
         * Sets the value of the locale property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiziType.Prestito.Locale }
         *     
         */
        public void setLocale(ServiziType.Prestito.Locale value) {
            this.locale = value;
        }

        /**
         * Gets the value of the interbibliotecario property.
         * 
         * @return
         *     possible object is
         *     {@link ServiziType.Prestito.Interbibliotecario }
         *     
         */
        public ServiziType.Prestito.Interbibliotecario getInterbibliotecario() {
            return interbibliotecario;
        }

        /**
         * Sets the value of the interbibliotecario property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiziType.Prestito.Interbibliotecario }
         *     
         */
        public void setInterbibliotecario(ServiziType.Prestito.Interbibliotecario value) {
            this.interbibliotecario = value;
        }

        /**
         * Gets the value of the materialiEsclusiLocale property.
         * 
         * @return
         *     possible object is
         *     {@link ServiziType.Prestito.MaterialiEsclusiLocale }
         *     
         */
        public ServiziType.Prestito.MaterialiEsclusiLocale getMaterialiEsclusiLocale() {
            return materialiEsclusiLocale;
        }

        /**
         * Sets the value of the materialiEsclusiLocale property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiziType.Prestito.MaterialiEsclusiLocale }
         *     
         */
        public void setMaterialiEsclusiLocale(ServiziType.Prestito.MaterialiEsclusiLocale value) {
            this.materialiEsclusiLocale = value;
        }

        /**
         * Gets the value of the riproduzioni property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the riproduzioni property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRiproduzioni().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiziType.Prestito.Riproduzioni }
         * 
         * 
         */
        public List<ServiziType.Prestito.Riproduzioni> getRiproduzioni() {
            if (riproduzioni == null) {
                riproduzioni = new ArrayList<ServiziType.Prestito.Riproduzioni>();
            }
            return this.riproduzioni;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tipo-prestito" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
         *                   &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
         *                   &lt;element name="ruolo">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;enumeration value="POS"/>
         *                         &lt;enumeration value="DSC"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="automatizzato" type="{}siNoType" minOccurs="0"/>
         *         &lt;element name="totale-prestiti" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="sistema-ill" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tipoPrestito",
            "automatizzato",
            "totalePrestiti",
            "sistemaIll"
        })
        public static class Interbibliotecario {

            @XmlElement(name = "tipo-prestito")
            protected List<ServiziType.Prestito.Interbibliotecario.TipoPrestito> tipoPrestito;
            protected SiNoType automatizzato;
            @XmlElement(name = "totale-prestiti")
            protected BigDecimal totalePrestiti;
            @XmlElement(name = "sistema-ill")
            protected List<ServiziType.Prestito.Interbibliotecario.SistemaIll> sistemaIll;

            /**
             * Gets the value of the tipoPrestito property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tipoPrestito property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTipoPrestito().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ServiziType.Prestito.Interbibliotecario.TipoPrestito }
             * 
             * 
             */
            public List<ServiziType.Prestito.Interbibliotecario.TipoPrestito> getTipoPrestito() {
                if (tipoPrestito == null) {
                    tipoPrestito = new ArrayList<ServiziType.Prestito.Interbibliotecario.TipoPrestito>();
                }
                return this.tipoPrestito;
            }

            /**
             * Gets the value of the automatizzato property.
             * 
             * @return
             *     possible object is
             *     {@link SiNoType }
             *     
             */
            public SiNoType getAutomatizzato() {
                return automatizzato;
            }

            /**
             * Sets the value of the automatizzato property.
             * 
             * @param value
             *     allowed object is
             *     {@link SiNoType }
             *     
             */
            public void setAutomatizzato(SiNoType value) {
                this.automatizzato = value;
            }

            /**
             * Gets the value of the totalePrestiti property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalePrestiti() {
                return totalePrestiti;
            }

            /**
             * Sets the value of the totalePrestiti property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalePrestiti(BigDecimal value) {
                this.totalePrestiti = value;
            }

            /**
             * Gets the value of the sistemaIll property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sistemaIll property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSistemaIll().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ServiziType.Prestito.Interbibliotecario.SistemaIll }
             * 
             * 
             */
            public List<ServiziType.Prestito.Interbibliotecario.SistemaIll> getSistemaIll() {
                if (sistemaIll == null) {
                    sistemaIll = new ArrayList<ServiziType.Prestito.Interbibliotecario.SistemaIll>();
                }
                return this.sistemaIll;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class SistemaIll {

                @XmlElement(required = true)
                protected String nome;
                protected String note;

                /**
                 * Gets the value of the nome property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNome() {
                    return nome;
                }

                /**
                 * Sets the value of the nome property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNome(String value) {
                    this.nome = value;
                }

                /**
                 * Gets the value of the note property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNote() {
                    return note;
                }

                /**
                 * Sets the value of the note property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNote(String value) {
                    this.note = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
             *         &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
             *         &lt;element name="ruolo">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;enumeration value="POS"/>
             *               &lt;enumeration value="DSC"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "internazionale",
                "nazionale",
                "ruolo"
            })
            public static class TipoPrestito {

                protected SiNoType internazionale;
                protected SiNoType nazionale;
                @XmlElement(required = true)
                protected String ruolo;

                /**
                 * Gets the value of the internazionale property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SiNoType }
                 *     
                 */
                public SiNoType getInternazionale() {
                    return internazionale;
                }

                /**
                 * Sets the value of the internazionale property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SiNoType }
                 *     
                 */
                public void setInternazionale(SiNoType value) {
                    this.internazionale = value;
                }

                /**
                 * Gets the value of the nazionale property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SiNoType }
                 *     
                 */
                public SiNoType getNazionale() {
                    return nazionale;
                }

                /**
                 * Sets the value of the nazionale property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SiNoType }
                 *     
                 */
                public void setNazionale(SiNoType value) {
                    this.nazionale = value;
                }

                /**
                 * Gets the value of the ruolo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRuolo() {
                    return ruolo;
                }

                /**
                 * Sets the value of the ruolo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRuolo(String value) {
                    this.ruolo = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="automatizzato" type="{}siNoType" minOccurs="0"/>
         *         &lt;element name="materiale-escluso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="durata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="utenti-ammessi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="totale-prestiti" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Locale {

            protected SiNoType automatizzato;
            @XmlElement(name = "materiale-escluso")
            protected String materialeEscluso;
            protected String durata;
            @XmlElement(name = "utenti-ammessi")
            protected String utentiAmmessi;
            @XmlElement(name = "totale-prestiti")
            protected BigDecimal totalePrestiti;

            /**
             * Gets the value of the automatizzato property.
             * 
             * @return
             *     possible object is
             *     {@link SiNoType }
             *     
             */
            public SiNoType getAutomatizzato() {
                return automatizzato;
            }

            /**
             * Sets the value of the automatizzato property.
             * 
             * @param value
             *     allowed object is
             *     {@link SiNoType }
             *     
             */
            public void setAutomatizzato(SiNoType value) {
                this.automatizzato = value;
            }

            /**
             * Gets the value of the materialeEscluso property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaterialeEscluso() {
                return materialeEscluso;
            }

            /**
             * Sets the value of the materialeEscluso property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaterialeEscluso(String value) {
                this.materialeEscluso = value;
            }

            /**
             * Gets the value of the durata property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDurata() {
                return durata;
            }

            /**
             * Sets the value of the durata property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDurata(String value) {
                this.durata = value;
            }

            /**
             * Gets the value of the utentiAmmessi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUtentiAmmessi() {
                return utentiAmmessi;
            }

            /**
             * Sets the value of the utentiAmmessi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUtentiAmmessi(String value) {
                this.utentiAmmessi = value;
            }

            /**
             * Gets the value of the totalePrestiti property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTotalePrestiti() {
                return totalePrestiti;
            }

            /**
             * Sets the value of the totalePrestiti property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTotalePrestiti(BigDecimal value) {
                this.totalePrestiti = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="materiale" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "materiale"
        })
        public static class MaterialiEsclusiLocale {

            @XmlElement(required = true)
            protected List<String> materiale;

            /**
             * Gets the value of the materiale property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the materiale property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMateriale().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getMateriale() {
                if (materiale == null) {
                    materiale = new ArrayList<String>();
                }
                return this.materiale;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="locale" type="{}siNoType" minOccurs="0"/>
         *         &lt;element name="nazionale" type="{}siNoType" minOccurs="0"/>
         *         &lt;element name="internazionale" type="{}siNoType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tipo",
            "locale",
            "nazionale",
            "internazionale"
        })
        public static class Riproduzioni {

            @XmlElement(required = true)
            protected String tipo;
            protected SiNoType locale;
            protected SiNoType nazionale;
            protected SiNoType internazionale;

            /**
             * Gets the value of the tipo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipo() {
                return tipo;
            }

            /**
             * Sets the value of the tipo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipo(String value) {
                this.tipo = value;
            }

            /**
             * Gets the value of the locale property.
             * 
             * @return
             *     possible object is
             *     {@link SiNoType }
             *     
             */
            public SiNoType getLocale() {
                return locale;
            }

            /**
             * Sets the value of the locale property.
             * 
             * @param value
             *     allowed object is
             *     {@link SiNoType }
             *     
             */
            public void setLocale(SiNoType value) {
                this.locale = value;
            }

            /**
             * Gets the value of the nazionale property.
             * 
             * @return
             *     possible object is
             *     {@link SiNoType }
             *     
             */
            public SiNoType getNazionale() {
                return nazionale;
            }

            /**
             * Sets the value of the nazionale property.
             * 
             * @param value
             *     allowed object is
             *     {@link SiNoType }
             *     
             */
            public void setNazionale(SiNoType value) {
                this.nazionale = value;
            }

            /**
             * Gets the value of the internazionale property.
             * 
             * @return
             *     possible object is
             *     {@link SiNoType }
             *     
             */
            public SiNoType getInternazionale() {
                return internazionale;
            }

            /**
             * Sets the value of the internazionale property.
             * 
             * @param value
             *     allowed object is
             *     {@link SiNoType }
             *     
             */
            public void setInternazionale(SiNoType value) {
                this.internazionale = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sezione" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sezione"
    })
    public static class SezioniSpeciali {

        @XmlElement(required = true)
        protected List<String> sezione;

        /**
         * Gets the value of the sezione property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sezione property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSezione().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSezione() {
            if (sezione == null) {
                sezione = new ArrayList<String>();
            }
            return this.sezione;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="sistema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Sistemi {

        @XmlElement(required = true)
        protected String sistema;

        /**
         * Gets the value of the sistema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSistema() {
            return sistema;
        }

        /**
         * Sets the value of the sistema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSistema(String value) {
            this.sistema = value;
        }

    }

}
