//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package it.sbn.iccu.abi.xml.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Si noti che comunque questo tipo è derivato da
 * 				"formaType" e quindi eredita le sue caratteristiche.
 * 			
 * 
 * <p>Java class for digitaleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="digitaleType">
 *   &lt;complexContent>
 *     &lt;extension base="{}formaType">
 *       &lt;all>
 *         &lt;element name="supporto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "digitaleType", propOrder = {
    "supporto"
})
public class DigitaleType
    extends FormaType
{

    protected String supporto;

    /**
     * Gets the value of the supporto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupporto() {
        return supporto;
    }

    /**
     * Sets the value of the supporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupporto(String value) {
        this.supporto = value;
    }

}
