//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package it.sbn.iccu.abi.xml.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.sbn.iccu.abi.xml.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.sbn.iccu.abi.xml.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiziType }
     * 
     */
    public ServiziType createServiziType() {
        return new ServiziType();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.DestinazioniSociali }
     * 
     */
    public ServiziType.Accesso.DestinazioniSociali createServiziTypeAccessoDestinazioniSociali() {
        return new ServiziType.Accesso.DestinazioniSociali();
    }

    /**
     * Create an instance of {@link ServiziType.SezioniSpeciali }
     * 
     */
    public ServiziType.SezioniSpeciali createServiziTypeSezioniSpeciali() {
        return new ServiziType.SezioniSpeciali();
    }

    /**
     * Create an instance of {@link Biblioteche }
     * 
     */
    public Biblioteche createBiblioteche() {
        return new Biblioteche();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti }
     * 
     */
    public AnagraficaType.Contatti createAnagraficaTypeContatti() {
        return new AnagraficaType.Contatti();
    }

    /**
     * Create an instance of {@link CatalogoSpecialeType.Copertura }
     * 
     */
    public CatalogoSpecialeType.Copertura createCatalogoSpecialeTypeCopertura() {
        return new CatalogoSpecialeType.Copertura();
    }

    /**
     * Create an instance of {@link AnagraficaType.Istituzione }
     * 
     */
    public AnagraficaType.Istituzione createAnagraficaTypeIstituzione() {
        return new AnagraficaType.Istituzione();
    }

    /**
     * Create an instance of {@link AmministrativaType.Personale }
     * 
     */
    public AmministrativaType.Personale createAmministrativaTypePersonale() {
        return new AmministrativaType.Personale();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti.Altro }
     * 
     */
    public AnagraficaType.Contatti.Altro createAnagraficaTypeContattiAltro() {
        return new AnagraficaType.Contatti.Altro();
    }

    /**
     * Create an instance of {@link CatalogoType.Copertura }
     * 
     */
    public CatalogoType.Copertura createCatalogoTypeCopertura() {
        return new CatalogoType.Copertura();
    }

    /**
     * Create an instance of {@link ServiziType.Orario }
     * 
     */
    public ServiziType.Orario createServiziTypeOrario() {
        return new ServiziType.Orario();
    }

    /**
     * Create an instance of {@link FormaType }
     * 
     */
    public FormaType createFormaType() {
        return new FormaType();
    }

    /**
     * Create an instance of {@link ServiziType.Orario.Chiusura }
     * 
     */
    public ServiziType.Orario.Chiusura createServiziTypeOrarioChiusura() {
        return new ServiziType.Orario.Chiusura();
    }

    /**
     * Create an instance of {@link AmministrativaType.Bilancio.Uscite }
     * 
     */
    public AmministrativaType.Bilancio.Uscite createAmministrativaTypeBilancioUscite() {
        return new AmministrativaType.Bilancio.Uscite();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso }
     * 
     */
    public ServiziType.Accesso createServiziTypeAccesso() {
        return new ServiziType.Accesso();
    }

    /**
     * Create an instance of {@link AnagraficaType.Nome }
     * 
     */
    public AnagraficaType.Nome createAnagraficaTypeNome() {
        return new AnagraficaType.Nome();
    }

    /**
     * Create an instance of {@link SpecializzazioneType }
     * 
     */
    public SpecializzazioneType createSpecializzazioneType() {
        return new SpecializzazioneType();
    }

    /**
     * Create an instance of {@link OrarioType }
     * 
     */
    public OrarioType createOrarioType() {
        return new OrarioType();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture }
     * 
     */
    public AmministrativaType.Strutture createAmministrativaTypeStrutture() {
        return new AmministrativaType.Strutture();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Locale }
     * 
     */
    public ServiziType.Prestito.Locale createServiziTypePrestitoLocale() {
        return new ServiziType.Prestito.Locale();
    }

    /**
     * Create an instance of {@link OrarioType.Orario }
     * 
     */
    public OrarioType.Orario createOrarioTypeOrario() {
        return new OrarioType.Orario();
    }

    /**
     * Create an instance of {@link AnagraficaType }
     * 
     */
    public AnagraficaType createAnagraficaType() {
        return new AnagraficaType();
    }

    /**
     * Create an instance of {@link DigitaleType }
     * 
     */
    public DigitaleType createDigitaleType() {
        return new DigitaleType();
    }

    /**
     * Create an instance of {@link CatalogoCollettivoType }
     * 
     */
    public CatalogoCollettivoType createCatalogoCollettivoType() {
        return new CatalogoCollettivoType();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.CondizioniAccesso.Documenti }
     * 
     */
    public ServiziType.Accesso.CondizioniAccesso.Documenti createServiziTypeAccessoCondizioniAccessoDocumenti() {
        return new ServiziType.Accesso.CondizioniAccesso.Documenti();
    }

    /**
     * Create an instance of {@link CatalogoSpecialeType }
     * 
     */
    public CatalogoSpecialeType createCatalogoSpecialeType() {
        return new CatalogoSpecialeType();
    }

    /**
     * Create an instance of {@link BibliotecaType }
     * 
     */
    public BibliotecaType createBibliotecaType() {
        return new BibliotecaType();
    }

    /**
     * Create an instance of {@link AmministrativaType.DepositoLegale }
     * 
     */
    public AmministrativaType.DepositoLegale createAmministrativaTypeDepositoLegale() {
        return new AmministrativaType.DepositoLegale();
    }

    /**
     * Create an instance of {@link FondoAnticoType }
     * 
     */
    public FondoAnticoType createFondoAnticoType() {
        return new FondoAnticoType();
    }

    /**
     * Create an instance of {@link CataloghiType }
     * 
     */
    public CataloghiType createCataloghiType() {
        return new CataloghiType();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture.Superficie }
     * 
     */
    public AmministrativaType.Strutture.Superficie createAmministrativaTypeStruttureSuperficie() {
        return new AmministrativaType.Strutture.Superficie();
    }

    /**
     * Create an instance of {@link AmministrativaType.Ente }
     * 
     */
    public AmministrativaType.Ente createAmministrativaTypeEnte() {
        return new AmministrativaType.Ente();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Interbibliotecario.TipoPrestito }
     * 
     */
    public ServiziType.Prestito.Interbibliotecario.TipoPrestito createServiziTypePrestitoInterbibliotecarioTipoPrestito() {
        return new ServiziType.Prestito.Interbibliotecario.TipoPrestito();
    }

    /**
     * Create an instance of {@link PatrimonioType }
     * 
     */
    public PatrimonioType createPatrimonioType() {
        return new PatrimonioType();
    }

    /**
     * Create an instance of {@link MaterialeType }
     * 
     */
    public MaterialeType createMaterialeType() {
        return new MaterialeType();
    }

    /**
     * Create an instance of {@link CatalogoCollettivoType.Zona }
     * 
     */
    public CatalogoCollettivoType.Zona createCatalogoCollettivoTypeZona() {
        return new CatalogoCollettivoType.Zona();
    }

    /**
     * Create an instance of {@link ServiziType.InformazioniBibliografiche }
     * 
     */
    public ServiziType.InformazioniBibliografiche createServiziTypeInformazioniBibliografiche() {
        return new ServiziType.InformazioniBibliografiche();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Interbibliotecario.SistemaIll }
     * 
     */
    public ServiziType.Prestito.Interbibliotecario.SistemaIll createServiziTypePrestitoInterbibliotecarioSistemaIll() {
        return new ServiziType.Prestito.Interbibliotecario.SistemaIll();
    }

    /**
     * Create an instance of {@link AmministrativaType.Regolamento }
     * 
     */
    public AmministrativaType.Regolamento createAmministrativaTypeRegolamento() {
        return new AmministrativaType.Regolamento();
    }

    /**
     * Create an instance of {@link CatalogoType.Forme }
     * 
     */
    public CatalogoType.Forme createCatalogoTypeForme() {
        return new CatalogoType.Forme();
    }

    /**
     * Create an instance of {@link AnnoSecoloType }
     * 
     */
    public AnnoSecoloType createAnnoSecoloType() {
        return new AnnoSecoloType();
    }

    /**
     * Create an instance of {@link ServiziType.Internet }
     * 
     */
    public ServiziType.Internet createServiziTypeInternet() {
        return new ServiziType.Internet();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti.Telefonico }
     * 
     */
    public AnagraficaType.Contatti.Telefonico createAnagraficaTypeContattiTelefonico() {
        return new AnagraficaType.Contatti.Telefonico();
    }

    /**
     * Create an instance of {@link AmministrativaType.Bilancio }
     * 
     */
    public AmministrativaType.Bilancio createAmministrativaTypeBilancio() {
        return new AmministrativaType.Bilancio();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Interbibliotecario }
     * 
     */
    public ServiziType.Prestito.Interbibliotecario createServiziTypePrestitoInterbibliotecario() {
        return new ServiziType.Prestito.Interbibliotecario();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.MaterialiEsclusiLocale }
     * 
     */
    public ServiziType.Prestito.MaterialiEsclusiLocale createServiziTypePrestitoMaterialiEsclusiLocale() {
        return new ServiziType.Prestito.MaterialiEsclusiLocale();
    }

    /**
     * Create an instance of {@link InfCarType }
     * 
     */
    public InfCarType createInfCarType() {
        return new InfCarType();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture.Postazioni }
     * 
     */
    public AmministrativaType.Strutture.Postazioni createAmministrativaTypeStrutturePostazioni() {
        return new AmministrativaType.Strutture.Postazioni();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.DestinazioniSociali.Destinazione }
     * 
     */
    public ServiziType.Accesso.DestinazioniSociali.Destinazione createServiziTypeAccessoDestinazioniSocialiDestinazione() {
        return new ServiziType.Accesso.DestinazioniSociali.Destinazione();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Riproduzioni }
     * 
     */
    public ServiziType.Prestito.Riproduzioni createServiziTypePrestitoRiproduzioni() {
        return new ServiziType.Prestito.Riproduzioni();
    }

    /**
     * Create an instance of {@link ServiziType.Sistemi }
     * 
     */
    public ServiziType.Sistemi createServiziTypeSistemi() {
        return new ServiziType.Sistemi();
    }

    /**
     * Create an instance of {@link AmministrativaType }
     * 
     */
    public AmministrativaType createAmministrativaType() {
        return new AmministrativaType();
    }

    /**
     * Create an instance of {@link CatalogoSpecialeType.Forme }
     * 
     */
    public CatalogoSpecialeType.Forme createCatalogoSpecialeTypeForme() {
        return new CatalogoSpecialeType.Forme();
    }

    /**
     * Create an instance of {@link AnagraficaType.Edificio }
     * 
     */
    public AnagraficaType.Edificio createAnagraficaTypeEdificio() {
        return new AnagraficaType.Edificio();
    }

    /**
     * Create an instance of {@link AnagraficaType.Indirizzo }
     * 
     */
    public AnagraficaType.Indirizzo createAnagraficaTypeIndirizzo() {
        return new AnagraficaType.Indirizzo();
    }

    /**
     * Create an instance of {@link ServiziType.InformazioniBibliografiche.ServizioEsterno }
     * 
     */
    public ServiziType.InformazioniBibliografiche.ServizioEsterno createServiziTypeInformazioniBibliograficheServizioEsterno() {
        return new ServiziType.InformazioniBibliografiche.ServizioEsterno();
    }

    /**
     * Create an instance of {@link AmministrativaType.Utenti }
     * 
     */
    public AmministrativaType.Utenti createAmministrativaTypeUtenti() {
        return new AmministrativaType.Utenti();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.CondizioniAccesso.Eta }
     * 
     */
    public ServiziType.Accesso.CondizioniAccesso.Eta createServiziTypeAccessoCondizioniAccessoEta() {
        return new ServiziType.Accesso.CondizioniAccesso.Eta();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture.Scaffalature }
     * 
     */
    public AmministrativaType.Strutture.Scaffalature createAmministrativaTypeStruttureScaffalature() {
        return new AmministrativaType.Strutture.Scaffalature();
    }

    /**
     * Create an instance of {@link CatalogoType }
     * 
     */
    public CatalogoType createCatalogoType() {
        return new CatalogoType();
    }

    /**
     * Create an instance of {@link FondoSpecialeType }
     * 
     */
    public FondoSpecialeType createFondoSpecialeType() {
        return new FondoSpecialeType();
    }

    /**
     * Create an instance of {@link AmministrativaType.CartaServizi }
     * 
     */
    public AmministrativaType.CartaServizi createAmministrativaTypeCartaServizi() {
        return new AmministrativaType.CartaServizi();
    }

    /**
     * Create an instance of {@link AnagraficaType.Codici }
     * 
     */
    public AnagraficaType.Codici createAnagraficaTypeCodici() {
        return new AnagraficaType.Codici();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.CondizioniAccesso }
     * 
     */
    public ServiziType.Accesso.CondizioniAccesso createServiziTypeAccessoCondizioniAccesso() {
        return new ServiziType.Accesso.CondizioniAccesso();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito }
     * 
     */
    public ServiziType.Prestito createServiziTypePrestito() {
        return new ServiziType.Prestito();
    }

    /**
     * Create an instance of {@link ServiziType.Orario.Variazione }
     * 
     */
    public ServiziType.Orario.Variazione createServiziTypeOrarioVariazione() {
        return new ServiziType.Orario.Variazione();
    }

}
