//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 03:22:19 PM CET 
//


package it.sbn.iccu.abi.xml.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipoDocType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tipoDocType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="documentoIdentità"/>
 *     &lt;enumeration value="tesseraBiblioteca"/>
 *     &lt;enumeration value="letteraPresentazione"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tipoDocType")
@XmlEnum
public enum TipoDocType {

    @XmlEnumValue("documentoIdentit\u00e0")
    DOCUMENTO_IDENTITÀ("documentoIdentit\u00e0"),
    @XmlEnumValue("tesseraBiblioteca")
    TESSERA_BIBLIOTECA("tesseraBiblioteca"),
    @XmlEnumValue("letteraPresentazione")
    LETTERA_PRESENTAZIONE("letteraPresentazione");
    private final String value;

    TipoDocType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoDocType fromValue(String v) {
        for (TipoDocType c: TipoDocType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
